all: speck_analysis speck_ddt

speck_analysis: 
	g++ -O3 -std=c++14 -fopenmp -march=native -o speck_analysis speck.cpp

speck_ddt:
	g++ -O3 -std=c++14 -fopenmp -march=native -o speck_ddt speck_ddt.cpp
